swagger: "2.0"
info:
  description: "Voici la documentation des API du projet Express CESI disponible sur le repository [https://github.com/Loise/express-cesi](https://github.com/Loise/express-cesi)"
  version: "1.0.0"
  title: "Swagger Express CESI 2022"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "loise.fenoll@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/"
tags:
- name: "student"
  description: "Gestion des étudiants"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /student:
    get:
      tags:
      - "student"
      summary: "Liste des étudiants"
      responses:
        "200":
          description: "Success"
definitions:
  Student:
    type: "object"
    required:
    - "name"
    - "age"
    properties:
      name:
        type: "string"
        example: "harry potter"
      age:
        type: "integer"
        example: 22
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"